### ISSUE TITLE
Problem in system generated link

### ISSUE THREAD

**Issue by RitadipBharati** [sdgniser/arc#16]
The system generated link has http://localhost:8000/ address upon which its showing "localhost refused to connect" and not connecting.

**Comment by Krishnakantparida** [comment]
I am facing the same issue regarding verification of email address for NISER Archive.

**Comment by PeithonKing** [comment]
I had the same issue while resetting my password. The password reset link was like this:
http://localhost:8000/arc/reset/some_bullshit_here/

I clicked on it and it didn't work, but when I changed it to:
http://10.0.2.35/arc/reset/some_bullshit_here/

It worked just fine!

So, long story short, until the person responsible for maintenance mends it, you can just replace "localhost:8000" part with "10.0.2.35" (SDG server IP address) and it will work.

**Comment by 11DE784A** [comment]
It was a problem with deployment on the server and has since been fixed thanks to @Abhishek-Deshmukh.
