### ISSUE TITLE
Opens only on the intranet

### ISSUE THREAD

**Issue by chandan-kumarsahu** [sdgniser/arc#28]
1. The NISER Archives that most of us use opens only through intranet which sometimes acts as a limitation when the NISER internet is down for hours and people have exams/quizzes for which they want to prepare.
2. This will also help people who want to use it from their homes or institutions outside NISER.

Kindly try to add it on the public web so that people can access it remotely and hassle-freely.

**Comment by Methaphur** [comment]
Won't be fixed. archive will stay on the intranet
