### ISSUE TITLE
Incorrect Password Reset Link

### ISSUE THREAD

**Issue by royabhinav-astro** [sdgniser/arc#33]
When students like me who don't even remember setting up a password for NISER Archive try to log in they just hit "Forgot Password" and generate a link to reset the password. But the password reset link they receive is incorrect.

![image](https://user-images.githubusercontent.com/72131607/191595731-dcda662e-96a3-495a-94ff-1d394f71cea3.png)

This link is of form http://10.0.2.35/arc//arc/reset/ODE/XXXXXXXXXXXXXX/, but it should actually be of form http://10.0.2.35/arc/reset/ODE/XXXXXXXXXXXXXX/. Please correct it.

**Comment by rahul3613** [comment]
Corrected Now.
Thanks for reporting it.
