### ISSUE TITLE
Handle non-unique keys gracefully

### ISSUE THREAD

**Issue by JeS24** [sdgniser/arc#9]
Gotta make this robust and transparent.
```
duplicate key value violates unique constraint "main_course_code_key"
DETAIL:  Key (code)=(p463) already exists.
```

**Comment by feynhat** [comment]
How to reproduce?

**Comment by JeS24** [comment]
@feynhat Seems to have been fixed. Can close.
![image](https://user-images.githubusercontent.com/31299799/108635194-1f172080-74a4-11eb-810c-40a5b2fee1a6.png)
